[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.34/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino

lib_deps =
    adafruit/Adafruit BNO08x