<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- ALL VALUES ARE PLACEHOLDERS -->
  	<xacro:property name="joint_effort" value="3.0"/>
  	<xacro:property name="joint_velocity" value="6.28318"/>
	<xacro:property name="joint_damping" value="0.0"/>
	<xacro:property name="joint_friction" value="0.0"/>
	
	<xacro:property name="link_mass" value="0.1"/>
	<xacro:property name="disk1_mass" value="0.12"/>
	<xacro:property name="disk2_mass" value="0.13"/>
	<xacro:property name="disk3_mass" value="0.14"/>
	<xacro:property name="end_effector_mass" value="0.1"/>
	<xacro:property name="probe_mass" value="0.05"/>
	
	<xacro:macro name="link_inertial" params="ixx iyy izz">
		<inertial>
			<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
			<mass value="${link_mass}"/>
			<inertia
				ixx="${ixx}" ixy="0.0" ixz="0.0"
				iyy="${iyy}" iyz="0.0"
				izz="${izz}"/>
		</inertial>
	</xacro:macro>
	
	<xacro:macro name="disk_inertial" params="mass ixx iyy izz">
		<inertial>
			<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
			<mass value="${mass}"/>
			<inertia
				ixx="${ixx}" ixy="0.0" ixz="0.0"
				iyy="${iyy}" iyz="0.0"
				izz="${izz}"/>
		</inertial>
	</xacro:macro>
	
	<xacro:macro name="material_collision" params="ref_link ambient diffuse specular">
		<gazebo reference="${ref_link}">
			<visual>
				<material>
					<ambient>${ambient}</ambient>
					<diffuse>${diffuse}</diffuse>
					<specular>${specular}</specular>
				</material>
			</visual>
		</gazebo>
	</xacro:macro>		
	
	<xacro:macro name="spm_mechanism" params="base_link prefix base_x base_y base_z">
	
	<!-- ONLY USING COLLISION MESHES FOR INITIAL TESTING -->
	<!-- REMEMBER TO ADD VISUAL/COLLISION MESHES!!!!~ -->

		<!--############-->
		<!-- LINK LINKS -->
		<!--############-->

		<link name="${prefix}link1">
			<xacro:link_inertial ixx="0.0001" iyy="0.0001" izz="0.0001"/>
			<visual>
				<geometry>
					<mesh filename="file://$(find spm_description)/meshes/link_collision.stl"/>
				</geometry>
				<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
			</visual>
			<collision>
				<geometry>
					<mesh filename="file://$(find spm_description)/meshes/link_collision.stl"/>
				</geometry>
				<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
			</collision>
		</link>
		
		<link name="${prefix}link2">
			<xacro:link_inertial ixx="0.0001" iyy="0.0001" izz="0.0001"/>
			<visual>
				<geometry>
					<mesh filename="file://$(find spm_description)/meshes/link_collision.stl"/>
				</geometry>
				<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
			</visual>
			<collision>
				<geometry>
					<mesh filename="file://$(find spm_description)/meshes/link_collision.stl"/>
				</geometry>
				<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
			</collision>
		</link>
		
		<link name="${prefix}link3">
			<xacro:link_inertial ixx="0.0001" iyy="0.0001" izz="0.0001"/>
			<visual>
				<geometry>
					<mesh filename="file://$(find spm_description)/meshes/link_collision.stl"/>
				</geometry>
				<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
			</visual>
			<collision>
				<geometry>
					<mesh filename="file://$(find spm_description)/meshes/link_collision.stl"/>
				</geometry>
				<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
			</collision>
		</link>
		
		<!--############-->
		<!-- DISK LINKS -->
		<!--############-->
		
		<link name="base_link"/>
		
		<link name="${prefix}disk1">
			<xacro:disk_inertial mass="${disk1_mass}" ixx="0.0001" iyy="0.0001" izz="0.0001"/>
			<visual>
				<geometry>
					<mesh filename="file://$(find spm_description)/meshes/disk1_collision.stl"/>
				</geometry>
				<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
			</visual>
			<collision>
				<geometry>
					<mesh filename="file://$(find spm_description)/meshes/disk1_collision.stl"/>
				</geometry>
				<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
			</collision>
		</link>
		
		<link name="${prefix}disk2">
			<xacro:disk_inertial mass="${disk2_mass}" ixx="0.0001" iyy="0.0001" izz="0.0001"/>
			<visual>
				<geometry>
					<mesh filename="file://$(find spm_description)/meshes/disk2_collision.stl"/>
				</geometry>
				<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
			</visual>
			<collision>
				<geometry>
					<mesh filename="file://$(find spm_description)/meshes/disk2_collision.stl"/>
				</geometry>
				<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
			</collision>
		</link>
		
		<link name="${prefix}disk3">
			<xacro:disk_inertial mass="${disk3_mass}" ixx="0.0001" iyy="0.0001" izz="0.0001"/>
			<visual>
				<geometry>
					<mesh filename="file://$(find spm_description)/meshes/disk3_collision.stl"/>
				</geometry>
				<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
			</visual>
			<collision>
				<geometry>
					<mesh filename="file://$(find spm_description)/meshes/disk3_collision.stl"/>
				</geometry>
				<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
			</collision>
		</link>

		<!--##############-->
		<!-- END EFFECTOR -->
		<!--##############-->
		
		<link name="${prefix}virtual_primary_link"/>

		<link name="${prefix}end_effector">
			<inertial>
				<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
				<mass value="${end_effector_mass}"/>
				<inertia
					ixx="0.10" ixy="0.0" ixz="0.0"
					iyy="0.05" iyz="0.0"
					izz="0.15"/>
			</inertial>
			<visual>
				<geometry>
					<mesh filename="file://$(find spm_description)/meshes/end_effector_collision.stl"/>
				</geometry>
				<origin xyz="0.049496 0.0 0.039663" rpy="0.0 ${-pi/3} 0.0"/>
			</visual>
			<collision>
				<geometry>
					<mesh filename="file://$(find spm_description)/meshes/end_effector_collision.stl"/>
				</geometry>
				<origin xyz="0.049496 0.0 0.039663" rpy="0.0 ${-pi/3} 0.0"/>
			</collision>
		</link>
		
		<!--#####################-->
		<!-- BASE TO DISK JOINTS -->
		<!--#####################-->
		
		<joint name="${prefix}disk1_to_base" type="continuous">
			<axis xyz="0.0 0.0 1.0"/>
			<limit effort="${joint_effort}" velocity="${joint_velocity}"/>
			<parent link="${prefix}base_link"/>
			<child link="${prefix}disk1"/>
			<origin xyz="${base_x} ${base_y} ${base_z}" rpy="0.0 0.0 0.0"/>
			<dynamics damping="${joint_damping}" friction="${joint_friction}"/>
		</joint>

		<joint name="${prefix}disk2_to_base" type="continuous">
			<axis xyz="0.0 0.0 1.0"/>
			<limit effort="${joint_effort}" velocity="${joint_velocity}"/>
			<parent link="${prefix}base_link"/>
			<child link="${prefix}disk2"/>
			<origin xyz="${base_x} ${base_y} ${base_z-0.00381}" rpy="0.0 0.0 0.0"/>
			<dynamics damping="${joint_damping}" friction="${joint_friction}"/>
		</joint>

		<joint name="${prefix}disk3_to_base" type="continuous">
			<axis xyz="0.0 0.0 1.0"/>
			<limit effort="${joint_effort}" velocity="${joint_velocity}"/>
			<parent link="${prefix}base_link"/>
			<child link="${prefix}disk3"/>
			<origin xyz="${base_x} ${base_y} ${base_z+0.01143}" rpy="0.0 0.0 0.0"/>
			<dynamics damping="${joint_damping}" friction="${joint_friction}"/>
		</joint>

		<!--#####################-->
		<!-- DISK TO LINK JOINTS -->	
		<!--#####################-->	

		<joint name="${prefix}link1_to_disk1" type="continuous">
			<axis xyz="0.0 0.0 1.0"/>
			<limit effort="${joint_effort}" velocity="${joint_velocity}"/>
			<parent link="${prefix}disk1"/>
			<child link="${prefix}link1"/>
			<origin xyz="0.0 0.060411 0.036634" rpy="${pi/4} 0.0 0.0"/>
			<dynamics damping="${joint_damping}" friction="${joint_friction}"/>
		</joint>

		<joint name="${prefix}link2_to_disk2" type="continuous">
			<axis xyz="0.0 0.0 1.0"/>
			<limit effort="${joint_effort}" velocity="${joint_velocity}"/>
			<parent link="${prefix}disk2"/>
			<child link="${prefix}link2"/>
			<origin xyz="0.052317 -0.030206 0.040444" rpy="${pi/4} 0.0 ${-2*pi/3}"/>
			<dynamics damping="${joint_damping}" friction="${joint_friction}"/>
		</joint>

		<joint name="${prefix}link3_to_disk3" type="continuous">
			<axis xyz="0.0 0.0 1.0"/>
			<limit effort="${joint_effort}" velocity="${joint_velocity}"/>
			<parent link="${prefix}disk3"/>
			<child link="${prefix}link3"/>
			<origin xyz="-0.052317 -0.030206 0.025204" rpy="${pi/4} 0.0 ${2*pi/3}"/>
			<dynamics damping="${joint_damping}" friction="${joint_friction}"/>
		</joint>

		<!--#############################-->
		<!-- LINK TO END EFFECTOR JOINTS -->
		<!--#############################-->
		
		<joint name="${prefix}primary_joint_ref" type="fixed">
			<parent link="${prefix}link1"/>
			<child link="${prefix}virtual_primary_link"/>
			<origin xyz="0.0 0.0 0.0" rpy="${-pi/4} 0.0 0.0"/>
		</joint>

		<joint name="${prefix}end_effector1_to_link1" type="continuous">
			<axis xyz="0.0 0.0 1.0"/>
			<limit effort="${joint_effort}" velocity="${joint_velocity}"/>
			<parent link="${prefix}virtual_primary_link"/>
			<child link="${prefix}end_effector"/>
			<origin xyz="-0.059097 -0.060411 0.026633" rpy="0.0 ${pi/3} 0.0"/>
			<dynamics damping="${joint_damping}" friction="${joint_friction}"/>
		</joint>


	</xacro:macro>

</robot>
		
	
	  
